add missing repair.h from dist generated tarball
  CC       fsck.o
../../../fsck/fsck.c:18:20: fatal error: repair.h: No such file or directory  #include repair.h
                    ^
compilation terminated.
Makefile:424: recipe for target 'fsck.o' failed
make[3]: *** [fsck.o] Error 1

Signed-off-by: Nicolas Boos <nicolas.boos@wanadoo.fr>
Signed-off-by: Namjae Jeon <linkinjeon@kernel.org>